name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Cache .stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
          key: stack-${{ hashFiles('stack.yaml') }}
      
      - name: Setup Haskell GHC
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 'latest'
          stack-version: 'latest'

      - name: Build with Stack
        run: stack build

      - name: Test with Stack
        run: stack test

  build_and_compress:
    name: Build and Compress
    needs: build_and_test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Haskell GHC
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 'latest'
          stack-version: 'latest'
          
      - name: Build with Make
        run: make

      - name: Compress Binary and Documentation
        run: |
          tar -czvf gladdos.tar.gz gladdos
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gladdos-package
          path: gladdos.tar.gz
  


  push_to_mirror:
    runs-on: ubuntu-latest
    needs: build_and_compress
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:EpitechPromo2026/B-FUN-500-MPL-5-1-glados-quentin.aumas.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
