name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Cache .stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
          key: stack-${{ hashFiles('stack.yaml') }}
      
      - name: Setup Haskell GHC
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 'latest'
          stack-version: 'latest'

      - name: Build with Stack
        run: stack build

      - name: Test with Stack
        run: stack test
    
  run_python_tests:
    name: Run Python Tests
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Build with Make
        run: make

      - name: Run Tests
        run: python test_fn.py

  build_and_compress:
    name: Build and Compress
    needs: run_python_tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Haskell GHC
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 'latest'
          stack-version: 'latest'
          
      - name: Build with Make
        run: make

      - name: Compress Binary and Documentation
        run: |
          tar -czvf gladdos.tar.gz gladdos
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gladdos-package
          path: gladdos.tar.gz
  


  push_to_mirror:
    runs-on: ubuntu-latest
    needs: build_and_compress
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:EpitechPromo2026/B-FUN-500-MPL-5-1-glados-quentin.aumas.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}


  release:
    needs: build_and_compress
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: gladdos-package
        path: release

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      with:
        tag_name: build-${{ github.run_id }}
        release_name: Release build-${{ github.run_id }}
        body: Description of the release build-${{ github.run_id }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/gladdos.tar.gz
        asset_name: gladdos.tar.gz
        asset_content_type: application/gzip
