# This is a basic workflow to help you get started with Actions

name: Haskell CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Haskell GHC
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 'latest'  # Use the latest GHC version
          stack-version: 'latest'  # Use the latest Cabal version
      - name: Build with Stack
        run: stack build
      - name: Test with Stack
        run: stack test


  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-FUN-500-MPL-5-1-glados-quentin.aumas.git
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }} 